# Final Allen brain electrophysiology data analysis

## Data pipeline

1. preparing raw data from allen brain institute using AllenSDK [notebook](./allen_data_analysis.ipynb)
1. Visualizing raw data using density plot [notebook](./allen_data_analysis.ipynb)
1. data processing for tensorflow learning from R data(incheol) [notebook](./data_processing_180227.ipynb)
    1. one-hot coding
    1. minmax scaling
    
## ANN learning pipeline

1. coarse searching hyperparameter(learning rate and L2 beta) = NO_1_output_input_coarse_searching.py
1. fine searching = NO_2_output_input_fine_searching.py
1. top 10 model tensorboard logging and model saving = NO_3_output_input_logging.py
1. selection top model by inspecting tensorboard log (./logs/output_input/)
1. top model restore and choosing best epoch step, saving results = NO_4_output_input_restore.py
1. all of the final results in ./results/

In [19]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import confusion_matrix

In [20]:
Eline_full_true = np.loadtxt('./results/EtestY_argmax.csv', delimiter = ',')
Eline_full_pred = np.loadtxt('./results/04_4_Eline_full_argmax.csv', delimiter= ',')
print('Accuracy:', '{:.4f}'.format(np.array(Eline_full_true == Eline_full_pred).sum()/(len(Eline_full_pred))))

Accuracy: 0.4588


In [22]:
confusion_matrix(Eline_full_true, Eline_full_pred)

array([[ 5,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  1,  0,  0,  5,  0,  4],
       [ 0,  0,  1,  0,  1,  0,  0,  0,  0],
       [ 0,  2,  0,  8,  0,  0,  1,  0,  1],
       [ 0,  0,  0,  0,  3,  2,  0,  0,  1],
       [ 1,  1,  0,  1,  0,  5,  1,  2,  0],
       [ 0,  0,  1,  5,  0,  3, 10,  1,  1],
       [ 0,  0,  0,  0,  0,  0,  1,  1,  4],
       [ 0,  0,  0,  0,  0,  0,  5,  1,  4]])

In [23]:
Eline_long_true = np.loadtxt('./results/Etest_longY_argmax.csv', delimiter = ',')
Eline_long_pred = np.loadtxt('./results/05_4_Eline_long_argmax.csv', delimiter= ',')
print('Accuracy:', '{:.4f}'.format(np.array(Eline_long_true == Eline_long_pred).sum()/(len(Eline_long_pred))))

Accuracy: 0.4588


In [24]:
confusion_matrix(Eline_long_true, Eline_long_pred)

array([[ 4,  0,  0,  0,  0,  0,  1,  0,  0],
       [ 0,  2,  0,  6,  0,  0,  3,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  2,  0,  2],
       [ 0,  0,  0,  0,  4,  2,  0,  0,  0],
       [ 0,  3,  0,  1,  0,  7,  0,  0,  0],
       [ 0,  1,  0,  1,  0,  4, 12,  1,  2],
       [ 1,  0,  0,  1,  0,  1,  1,  0,  2],
       [ 0,  0,  0,  3,  1,  0,  4,  0,  2]])

In [38]:
Eline_short_true = np.loadtxt('./results/Etest_shortY_argmax.csv', delimiter = ',')
Eline_short_pred = np.loadtxt('./results/06_4_Eline_short_argmax.csv', delimiter= ',')
print('Accuracy:', '{:.4f}'.format(np.array(Eline_short_true == Eline_short_pred).sum()/(len(Eline_short_pred))))

Accuracy: 0.3882


In [39]:
confusion_matrix(Eline_short_true, Eline_short_pred)

array([[ 2,  0,  0,  0,  0,  0,  3,  0,  0],
       [ 1,  0,  0,  5,  0,  1,  5,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  7,  0,  1,  4,  0,  0],
       [ 0,  0,  1,  0,  3,  1,  1,  0,  0],
       [ 1,  0,  0,  0,  2,  8,  0,  0,  0],
       [ 1,  0,  0,  2,  2,  3, 13,  0,  0],
       [ 1,  0,  0,  0,  0,  1,  4,  0,  0],
       [ 0,  0,  0,  1,  0,  3,  6,  0,  0]])

In [40]:
Eline_ramp_true = np.loadtxt('./results/Etest_rampY_argmax.csv', delimiter = ',')
Eline_ramp_pred = np.loadtxt('./results/07_4_Eline_ramp_argmax.csv', delimiter= ',')
print('Accuracy:', '{:.4f}'.format(np.array(Eline_ramp_true == Eline_ramp_pred).sum()/(len(Eline_ramp_pred))))

Accuracy: 0.4706


In [41]:
confusion_matrix(Eline_ramp_true, Eline_ramp_pred)

array([[ 5,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  1,  8,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  3,  0,  1],
       [ 0,  0,  1,  0,  5,  0,  0,  0,  0],
       [ 1,  0,  1,  0,  0,  5,  4,  0,  0],
       [ 0,  0,  1,  3,  3,  0, 14,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  5,  0,  0],
       [ 1,  0,  0,  2,  0,  0,  6,  0,  1]])

In [43]:
Iline_full_true = np.loadtxt('./results/ItestY_argmax.csv', delimiter = ',')
Iline_full_pred = np.loadtxt('./results/08_4_Iline_full_argmax.csv', delimiter= ',')
print('Accuracy:', '{:.4f}'.format(np.array(Iline_full_true == Iline_full_pred).sum()/(len(Iline_full_pred))))

Accuracy: 0.7077


In [45]:
confusion_matrix(Iline_full_true, Iline_full_pred)

array([[ 0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  1,  0,  0,  2,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  9,  0,  1,  4,  0],
       [ 0,  0,  0,  0,  2,  2,  0,  0],
       [ 0,  0,  0,  0,  0, 18,  2,  0],
       [ 0,  0,  0,  0,  0,  1, 16,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0]])

In [46]:
Iline_long_true = np.loadtxt('./results/Itest_longY_argmax.csv', delimiter = ',')
Iline_long_pred = np.loadtxt('./results/09_4_Iline_long_argmax.csv', delimiter= ',')
print('Accuracy:', '{:.4f}'.format(np.array(Iline_long_true == Iline_long_pred).sum()/(len(Iline_long_pred))))

Accuracy: 0.6923


In [47]:
confusion_matrix(Iline_long_true, Iline_long_pred)

array([[ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  2,  0,  0,  3,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  1,  2,  0],
       [ 0,  0,  0,  0,  2,  2,  0,  0],
       [ 0,  0,  0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  4,  0,  1, 12,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0]])

In [48]:
Iline_short_true = np.loadtxt('./results/Itest_shortY_argmax.csv', delimiter = ',')
Iline_short_pred = np.loadtxt('./results/10_4_Iline_short_argmax.csv', delimiter= ',')
print('Accuracy:', '{:.4f}'.format(np.array(Iline_short_true == Iline_short_pred).sum()/(len(Iline_short_pred))))

Accuracy: 0.6615


In [49]:
confusion_matrix(Iline_short_true, Iline_short_pred)

array([[ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  3,  0,  2,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0, 10,  0,  1,  3,  0],
       [ 0,  0,  0,  1,  1,  1,  1,  0],
       [ 0,  0,  0,  0,  0, 18,  2,  0],
       [ 0,  0,  0,  2,  1,  3, 11,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0]])

In [51]:
Iline_ramp_true = np.loadtxt('./results/Itest_rampY_argmax.csv', delimiter = ',')
Iline_ramp_pred = np.loadtxt('./results/11_4_Iline_ramp_argmax.csv', delimiter= ',')
print('Accuracy:', '{:.4f}'.format(np.array(Iline_ramp_true == Iline_ramp_pred).sum()/(len(Iline_ramp_pred))))

Accuracy: 0.6923


In [52]:
confusion_matrix(Iline_ramp_true, Iline_ramp_pred)

array([[ 0,  0,  0,  1,  0,  0,  0,  0],
       [ 0,  1,  0,  3,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0, 11,  0,  1,  2,  0],
       [ 0,  0,  0,  2,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0, 18,  2,  0],
       [ 0,  0,  0,  2,  0,  0, 15,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0]])